### ISSUE TITLE
Status of this project and this repository

### ISSUE THREAD

**Issue by lucc** [matasarei/JsonRPC#7]
It seems to me that you recently took over the maintainership of [fguillot/json-rpc on packagist](https://packagist.org/packages/fguillot/json-rpc).  I also noticed that the original source repository at https://github.com/fguillot/JsonRPC vanished. I have a couple of questions regarding the status of this repository and the package on packagist and your plans for the future. As this project has quite a few donwloads on packagist and forks here on Github I think some other people might also be interested in this information. Maybe there is an appropriate place to publish it?

- Are you planning on maintaining this repository for some time? 
- Do you think it can be used in production and will receive security updates?
- Why did you take over the repository?
- This one is more for @fguillot: Why did you abandon the project? Why did you delete your repository? Do you want to refer people to this repository? (your non existing repository is still in the google index)
- Where can we reach out to all the other users or forkers of this code to pull in some contributors now that the code is actively developed again?

**Comment by matasarei** [comment]
Hi @lucc !
Yes, as you see I decided to take care of this repository and already committed one small fix recently. I take control over repository for security and other reasons. We use it on few projects (on prod) and deploy was suddenly broken because of repo. I don't have any info about original author and I also want to know why...

About future development:
I can say only about security and bug fixes. It works perfect for us and I don't have plan to implement any new features, at least for now.

**Comment by lucc** [comment]
The homepage link on packagist still points to the old repo. You could change that.

**Comment by matasarei** [comment]
Yes, I will.

**Comment by lucc** [comment]
Thank you for the answer!! And also thank you for stepping up to keep the project alive (even if only for minimal bug fixes).

Maybe we should ping some active developers from the fork network here on github. What do you think? If we have more people interested in an active JsonRPC project it might be good.
